import { getProducts, saveProducts } from '../../../lib/cms';

export const GET = async () => {
    const products = await getProducts();
    return new Response(JSON.stringify(products), {
        status: 200,
        headers: { "Content-Type": "application/json" }
    });
};

export const POST = async ({ request }) => {
    try {
        const data = await request.json();
        const products = await getProducts();

        // Check if updating existing or creating new. Using ID or slug? 
        // Let's use 'id' generated by timestamp if new
        if (!data.id) data.id = Date.now().toString();

        const existingIndex = products.findIndex(p => p.id === data.id);

        if (existingIndex >= 0) {
            products[existingIndex] = { ...products[existingIndex], ...data };
        } else {
            products.push(data);
        }

        await saveProducts(products);
        return new Response(JSON.stringify({ success: true, id: data.id }), { status: 200 });
    } catch (e) {
        return new Response(JSON.stringify({ error: e.message }), { status: 500 });
    }
};
